"""
DMD Guidance Model for UNSB
Implements Distribution Matching Distillation loss with adversarial classifier
Based on DMD2: https://github.com/tianweiy/DMD2
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import copy

from .guided_diffusion_import import load_guided_diffusion
from .adm_wrapper import get_x0_from_noise

load_guided_diffusion()
from guided_diffusion.nn import timestep_embedding


class DMDGuidance(nn.Module):
    """
    DMD Guidance Model combining:
    - real_unet (mu_real): Pretrained ADM teacher (frozen)
    - fake_unet (mu_fake): Trainable student denoiser
    - cls_pred_branch: Adversarial classifier for real/fake discrimination
    """

    def __init__(self, opt, adm_wrapper, fake_adm_wrapper=None):
        super().__init__()
        self.opt = opt

        # mu_real: Pretrained ADM (frozen teacher)
        self.real_unet = adm_wrapper
        self.real_unet.freeze_parameters()

        # mu_fake: clone teacher UNet so structure/initial weights are identical at start
        if fake_adm_wrapper is None:
            self.fake_unet = copy.deepcopy(self.real_unet.unet)
        else:
            self.fake_unet = copy.deepcopy(fake_adm_wrapper.unet)
            # explicit safety in case external wrapper exposes frozen params
            self.fake_unet.requires_grad_(True)

        # Trainable fake_unet
        self.fake_unet.requires_grad_(True)

        self.num_train_timesteps = opt.num_train_timesteps

        # Timestep range for DM loss
        self.min_step = int(opt.min_step_percent * self.num_train_timesteps)
        self.max_step = int(opt.max_step_percent * self.num_train_timesteps)
        self.dm_denom_min = float(getattr(opt, "dm_denom_min", 1e-3))
        self.dm_grad_clip = float(getattr(opt, "dm_grad_clip", 10.0))

        # Use alphas from ADM wrapper (same schedule)
        self.alphas_cumprod = adm_wrapper.alphas_cumprod

        # Classifier branch for adversarial loss (real vs fake discrimination)
        # Only create if lambda_CLS > 0 (otherwise netD already does this job)
        if opt.lambda_CLS > 0:
            # Classifier on fake_unet bottleneck features (DMD2-style internal representation usage)
            bottleneck_channels = int(self.fake_unet.channel_mult[-1] * self.fake_unet.model_channels)
            self.cls_pred_branch = nn.Sequential(
                nn.Conv2d(bottleneck_channels, bottleneck_channels, kernel_size=3, stride=1, padding=1),
                nn.GroupNorm(num_groups=32, num_channels=bottleneck_channels),
                nn.SiLU(),
                nn.Conv2d(bottleneck_channels, bottleneck_channels, kernel_size=3, stride=2, padding=1),
                nn.GroupNorm(num_groups=32, num_channels=bottleneck_channels),
                nn.SiLU(),
                nn.Conv2d(bottleneck_channels, bottleneck_channels, kernel_size=3, stride=2, padding=1),
                nn.GroupNorm(num_groups=32, num_channels=bottleneck_channels),
                nn.SiLU(),
                nn.LeakyReLU(0.2, inplace=True),
                nn.AdaptiveAvgPool2d((1, 1)),
                nn.Conv2d(bottleneck_channels, 1, kernel_size=1)
            )
        else:
            self.cls_pred_branch = None

    def predict_noise(self, unet, noisy_image, timesteps):
        """
        Predict noise using given UNet

        Args:
            unet: The UNet model (real or fake)
            noisy_image: [B, C, H, W] noisy image
            timesteps: [B] timestep indices

        Returns:
            noise_pred: [B, C, H, W] predicted noise
        """
        if timesteps.dtype != torch.long:
            timesteps = timesteps.long()

        # Guided Diffusion UNet returns tensor directly (not a dict with .sample)
        model_output = unet(noisy_image, timesteps)

        # If learn_sigma=True, output is [B, 6, H, W] (noise + sigma)
        # We only need noise, so take first C channels
        C = noisy_image.shape[1]
        noise_pred = model_output[:, :C]

        return noise_pred

    def compute_distribution_matching_loss(self, clean_images):
        """
        Compute DMD2 distribution matching loss
        This is the core loss that matches the distributions of real_unet and fake_unet

        Args:
            clean_images: [B, C, H, W] clean images generated by UNSB netG (fake_B)

        Returns:
            loss_dict: Dictionary with 'loss_dm'
            log_dict: Dictionary with intermediate values for logging
        """
        original_images = clean_images
        batch_size = clean_images.shape[0]

        with torch.no_grad():
            # Sample random timesteps for DM loss
            timesteps = torch.randint(
                self.min_step,
                min(self.max_step + 1, self.num_train_timesteps),
                [batch_size],
                device=clean_images.device,
                dtype=torch.long
            )

            # Add noise to clean images using ADM wrapper's method
            noise = torch.randn_like(clean_images)
            noisy_images = self.real_unet.add_noise(clean_images, noise, timesteps)

            # Predict noise with fake_unet (student)
            pred_fake_noise = self.predict_noise(self.fake_unet, noisy_images, timesteps)
            pred_fake_image = get_x0_from_noise(
                noisy_images.float(),
                pred_fake_noise.float(),
                self.alphas_cumprod.float(),
                timesteps
            )

            # Predict noise with real_unet (teacher ADM)
            pred_real_noise = self.real_unet.predict_noise(noisy_images, timesteps)
            pred_real_image = get_x0_from_noise(
                noisy_images.float(),
                pred_real_noise.float(),
                self.alphas_cumprod.float(),
                timesteps
            )

            # Compute score difference (distribution matching gradient)
            # p = (clean_x0 - predicted_x0) is proportional to score
            p_real = (clean_images - pred_real_image)
            p_fake = (clean_images - pred_fake_image)

            # Normalized gradient for distribution matching
            denom = torch.abs(p_real).mean(dim=[1, 2, 3], keepdim=True).clamp_min(self.dm_denom_min)
            grad = (p_real - p_fake) / denom
            grad = torch.nan_to_num(grad)
            if self.dm_grad_clip > 0:
                grad = torch.clamp(grad, min=-self.dm_grad_clip, max=self.dm_grad_clip)

        # Distribution matching loss (SDS-like loss)
        # Gradients flow through original_images to update generator
        loss_dm = 0.5 * F.mse_loss(
            original_images.float(),
            (original_images - grad).detach().float(),
            reduction="mean"
        )

        loss_dict = {
            "loss_dm": loss_dm
        }

        log_dict = {
            "dmtrain_noisy_images": noisy_images.detach().float(),
            "dmtrain_pred_real_image": pred_real_image.detach().float(),
            "dmtrain_pred_fake_image": pred_fake_image.detach().float(),
            "dmtrain_grad": grad.detach(),
            "dmtrain_denom_mean": denom.detach().mean().float(),
            "dmtrain_grad_norm": torch.norm(grad.detach().float()),
            "dmtrain_timesteps": timesteps.detach(),
        }

        return loss_dict, log_dict

    def compute_loss_fake(self, clean_images):
        """
        Compute denoising loss for fake_unet (student model)
        This trains mu_fake to denoise properly

        Args:
            clean_images: [B, C, H, W] clean images
                MUST BE DETACHED by caller to prevent generator gradients

        Returns:
            loss_dict: Dictionary with 'loss_fake_mean'
            log_dict: Dictionary with logging info
        """
        batch_size = clean_images.shape[0]

        # Random timesteps
        timesteps = torch.randint(
            0,
            self.num_train_timesteps,
            [batch_size],
            device=clean_images.device,
            dtype=torch.long
        )

        # Add noise using ADM wrapper's method
        noise = torch.randn_like(clean_images)
        noisy_images = self.real_unet.add_noise(clean_images, noise, timesteps)

        # Predict noise with fake_unet
        pred_fake_noise = self.predict_noise(self.fake_unet, noisy_images, timesteps)
        fake_x0_pred = get_x0_from_noise(
            noisy_images.float(),
            pred_fake_noise.float(),
            self.alphas_cumprod.float(),
            timesteps
        )

        # Epsilon prediction loss (same objective as original DMD2 SD guidance)
        loss_fake = torch.mean((pred_fake_noise.float() - noise.float()) ** 2)

        loss_dict = {
            "loss_fake_mean": loss_fake
        }

        log_dict = {
            "faketrain_images": clean_images.detach(),
            "faketrain_noisy_images": noisy_images.detach(),
            "faketrain_x0_pred": fake_x0_pred.detach().float(),
            "faketrain_pred_noise_mean": pred_fake_noise.detach().float().mean(),
            "faketrain_pred_noise_std": pred_fake_noise.detach().float().std(),
            "faketrain_target_noise_mean": noise.detach().float().mean(),
            "faketrain_target_noise_std": noise.detach().float().std(),
            "faketrain_noise_mae": (pred_fake_noise.detach().float() - noise.detach().float()).abs().mean(),
        }

        return loss_dict, log_dict

    def extract_features(self, unet, image, timesteps, need_grad=False):
        """
        Extract intermediate features from UNet for classification
        Returns bottleneck features before final output.

        Args:
            unet: UNet model
            image: [B, C, H, W] input image
            timesteps: [B] timesteps
            need_grad: If True, allow gradients to flow (for generator cls loss).

        Returns:
            features: Bottleneck features for classifier
        """
        if timesteps.dtype != torch.long:
            timesteps = timesteps.long()

        def _forward(sample, unet, timesteps_embed):
            h = sample.type(unet.dtype)
            for module in unet.input_blocks:
                h = module(h, timesteps_embed)
            h = unet.middle_block(h, timesteps_embed)
            return h.type(sample.dtype)

        timesteps_embed = unet.time_embed(timestep_embedding(timesteps, unet.model_channels))
        if need_grad:
            sample = _forward(image, unet, timesteps_embed)
        else:
            with torch.no_grad():
                sample = _forward(image, unet, timesteps_embed)
        return sample

    def compute_cls_logits(self, images, timesteps, need_grad=False):
        """
        Compute classifier logits for real/fake discrimination.

        Args:
            images: [B, C, H, W] images (real_B or fake_B)
            timesteps: [B] timesteps (not used)
            need_grad: If True, allow gradients to flow to images (for generator cls loss).

        Returns:
            logits: [B] realism prediction logits
        """
        if self.cls_pred_branch is None:
            raise RuntimeError("Classifier not initialized. Set lambda_CLS > 0 to use classifier.")

        rep = self.extract_features(self.fake_unet, images, timesteps, need_grad=need_grad)
        logits = self.cls_pred_branch(rep.float()).squeeze(dim=[2, 3])
        return logits

    def compute_generator_cls_loss(self, fake_images, timesteps):
        """
        Adversarial loss for generator (fool the classifier).
        Uses need_grad=True so gradient flows to fake_images (netG output).
        """
        cls_logits = self.compute_cls_logits(fake_images, timesteps, need_grad=True)
        gen_cls_loss = F.softplus(-cls_logits).mean()
        return gen_cls_loss

    def compute_guidance_cls_loss(self, real_images, fake_images, timesteps):
        """
        Train classifier to distinguish real from fake images

        Args:
            real_images: [B, C, H, W] real images (real_B)
            fake_images: [B, C, H, W] fake images
                MUST BE DETACHED by caller to prevent generator gradients
            timesteps: [B] timesteps

        Returns:
            guidance_cls_loss: Classifier training loss
        """
        # DMD2 SD adversarial logits loss:
        # fake term: softplus(fake_logits), real term: softplus(-real_logits)
        cls_logits_real = self.compute_cls_logits(real_images, timesteps)
        cls_logits_fake = self.compute_cls_logits(fake_images, timesteps)
        guidance_cls_loss = F.softplus(cls_logits_fake).mean() + F.softplus(-cls_logits_real).mean()

        return guidance_cls_loss

    def forward(self, clean_images, real_images=None, generator_turn=True, guidance_turn=True):
        """
        Forward pass for training

        Args:
            clean_images: [B, C, H, W] generated clean images (fake_B)
            real_images: [B, C, H, W] real clean images (real_B) for classifier
            generator_turn: Whether to compute generator losses
            guidance_turn: Whether to compute guidance losses

        Returns:
            loss_dict: Dictionary of losses
            log_dict: Dictionary for logging
        """
        loss_dict = {}
        log_dict = {}

        timesteps = torch.zeros([clean_images.shape[0]], dtype=torch.long, device=clean_images.device)

        # Generator turn: compute DM loss and generator adversarial loss
        if generator_turn:
            dm_dict, dm_log_dict = self.compute_distribution_matching_loss(clean_images)
            loss_dict.update(dm_dict)
            log_dict.update(dm_log_dict)

            if self.opt.lambda_CLS > 0 and real_images is not None:
                gen_cls_loss = self.compute_generator_cls_loss(clean_images, timesteps)
                loss_dict['gen_cls_loss'] = gen_cls_loss

        # Guidance turn: compute fake_unet denoising loss and classifier loss
        if guidance_turn:
            fake_dict, fake_log_dict = self.compute_loss_fake(clean_images)
            loss_dict.update(fake_dict)
            log_dict.update(fake_log_dict)

            if self.opt.lambda_CLS > 0 and real_images is not None:
                guidance_cls_loss = self.compute_guidance_cls_loss(
                    real_images, clean_images, timesteps
                )
                loss_dict['guidance_cls_loss'] = guidance_cls_loss

        return loss_dict, log_dict
